from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
from .glm4v.nodes import NODE_CLASS_MAPPINGS as GLM4V_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GLM4V_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS.update(GLM4V_NODE_CLASS_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS.update(GLM4V_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
